feat: api get list account roles
dwarvesf/fortress-api pull request #10
Opened 2022-11-07 06:04 UTC by datphamcode295

What's this PR do?
create api to get list values for account roles
Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/55711201/200757015-8bd1effb-bc78-474d-8b1b-96a3942c9d51.png)

## Request
```
curl 'http://localhost:8200/api/v1/metadata/account-roles'
-H 'accept: /'
-H 'accept-language: vi,en-US;q=0.9,en;q=0.8'
-H 'content-type: application/json'
-H 'origin: http://localhost:3000/'
-H 'referer: http://localhost:3000/'
-H 'sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"'
-H 'sec-ch-ua-mobile: ?0'
-H 'sec-ch-ua-platform: "macOS"'
-H 'sec-fetch-dest: empty'
-H 'sec-fetch-mode: cors'
-H 'sec-fetch-site: cross-site'
-H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
--compressed
```

## Response
```
{
  "data": [
    {
      "id": "11ccffea-2cc9-4e98-9bef-3464dfe4dec8",
      "createdAt": "2022-11-07T09:50:25.714604Z",
      "updatedAt": "2022-11-07T09:50:25.714604Z",
      "name": "Admin",
      "code": "admin"
    },
    {
      "id": "d796884d-a8c4-4525-81e7-54a3b6099eac",
      "createdAt": "2022-11-07T09:50:25.714604Z",
      "updatedAt": "2022-11-07T09:50:25.714604Z",
      "name": "Member",
      "code": "member"
    }
  ]
}
```

2022-11-07 09:10 UTC, huynguyenh commented
phần này sẽ liên quan tới @namnhce , need help fren, maybe roles này permission Nam đang làm

2022-11-08 06:06 UTC, namnhce requested changes

2022-11-08 06:09 UTC, namnhce requested changes

2022-11-08 06:09 UTC, namnhce commented on pkg/store/store.go
>  	Employee   employee_store.IStore
```suggestion
	Employee   employee.IStore
```

2022-11-08 06:09 UTC, namnhce commented on pkg/store/store.go
> +		Role:       role_store.New(db),
```suggestion
		Role:       role.New(db),
```

2022-11-08 06:09 UTC, namnhce commented on pkg/store/store.go
>  		Employee:   employee_store.New(db),
```suggestion
		Employee:   employee.New(db),
```

2022-11-08 06:36 UTC, datphamcode295 commented on pkg/store/store.go
>  	Employee   employee_store.IStore
cái này là em đổi lại tên package employee_store luôn à anh

2022-11-09 05:13 UTC, namnhce requested changes

2022-11-09 05:13 UTC, namnhce commented on pkg/handler/metadata/metadata.go
> +// WorkingStatus godoc
```suggestion
// AccountRoles godoc
```

2022-11-09 05:13 UTC, namnhce commented on pkg/store/role/interface.go
> +package role_store
```suggestion
package role
```

2022-11-09 08:05 UTC, namnhce requested changes
Just a last request change.

2022-11-09 08:05 UTC, namnhce commented on pkg/handler/metadata/metadata.go
> +		"handler": "Roles",
```suggestion
		"handler": "AccountRoles",
```

2022-11-09 08:10 UTC, datphamcode295 commented on pkg/handler/metadata/metadata.go
> +		"handler": "Roles",
dạ em chỉnh lại cái này r á anh

2022-11-09 09:43 UTC, namnhce approved these changes

2022-11-09 09:43 UTC, namnhce commented
LGTM 👍

2022-11-09 09:48 UTC, merged