feat: api get list account statuses
dwarvesf/fortress-api pull request #11
Opened 2022-11-07 06:17 UTC by datphamcode295

####What's this PR do?
create api to get list values for account statuses 
####Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/55711201/200238888-4d34fe9d-0264-4a3b-b1c2-a1f1b34c5bb2.png)
// curl
curl 'http://localhost:8200/api/v1/metadata/account-statuses'
-H 'accept: /'
-H 'accept-language: vi,en-US;q=0.9,en;q=0.8'
-H 'content-type: application/json'
-H 'origin: http://localhost:3000/'
-H 'referer: http://localhost:3000/'
-H 'sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"'
-H 'sec-ch-ua-mobile: ?0'
-H 'sec-ch-ua-platform: "macOS"'
-H 'sec-fetch-dest: empty'
-H 'sec-fetch-mode: cors'
-H 'sec-fetch-site: cross-site'
-H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
--compressed

//response:
{"data":[{"id":"onboarding","name":"Onboarding"},{"id":"probation","name":"Probation"},{"id":"active","name":"Active"},{"id":"on-Leave","name":"On-Leave"}]}

2022-11-07 13:26 UTC, namnhce requested changes

2022-11-07 13:26 UTC, namnhce commented on pkg/handler/metadata/testdata/get_account_status/200.json
> +}
add newline

2022-11-08 01:03 UTC, datphamcode295 commented on pkg/handler/metadata/testdata/get_account_status/200.json
> +}
thanks you, it's done

2022-11-08 17:01 UTC, namnhce requested changes

2022-11-08 17:01 UTC, namnhce commented on pkg/store/account_status/account_status.go
> +package account_status_store
package name accountstatus
dir name: store/accountstatus

2022-11-09 01:20 UTC, datphamcode295 commented on migrations/schemas/20221108071900-add_account_statuses_table.sql
> +ALTER TABLE "employees" ADD CONSTRAINT fk_employee_account_statuses FOREIGN KEY ("account_status") REFERENCES "account_statuses" ("id");
em không chắc cái này lắm tại em đang đặt tên theo cú pháp trong file create user permission của anh á, nên em cũng hơi thắc mắc sao tên trong 2 trường hợp khác nhau ạ

2022-11-09 02:17 UTC, namnhce requested changes

2022-11-09 02:17 UTC, namnhce commented on migrations/schemas/20221108071900-add_account_statuses_table.sql
> +ALTER TABLE "employees" ADD CONSTRAINT fk_employee_account_statuses FOREIGN KEY ("account_status") REFERENCES "account_statuses" ("id");
À. cái đấy để a update lại sau nhé. Hồi đấy là a sai á

2022-11-09 02:40 UTC, namnhce requested changes

2022-11-09 02:40 UTC, namnhce commented on pkg/store/store.go
> +	accountstatus_store "github.com/dwarvesf/fortress-api/pkg/store/accountstatus"
```suggestion
	"github.com/dwarvesf/fortress-api/pkg/store/accountstatus"
```

2022-11-09 02:40 UTC, namnhce commented on pkg/view/metadata.go
> +	Data []model.AccountStatus `json:"data"`
Cái này nên define struct ở view nha. Rồi thêm hàm convert qua

2022-11-09 03:46 UTC, datphamcode295 commented on pkg/store/store.go
> +	accountstatus_store "github.com/dwarvesf/fortress-api/pkg/store/accountstatus"
cái này máy em nó lưu là nó tự thêm luôn á anh

2022-11-09 04:26 UTC, namnhce requested changes

2022-11-09 04:26 UTC, namnhce commented on pkg/store/store.go
> +	accountstatus_store "github.com/dwarvesf/fortress-api/pkg/store/accountstatus"
sao mà tự thêm được. Dưới cái function called của em nó đang dùng alias đấy

2022-11-09 04:46 UTC, namnhce requested changes

2022-11-09 04:46 UTC, namnhce commented on pkg/handler/metadata/metadata.go
> +// AccountStatus godoc
```suggestion
// AccountStatuses godoc
```

2022-11-09 05:06 UTC, namnhce requested changes

2022-11-09 05:06 UTC, namnhce commented on pkg/handler/metadata/metadata.go
> +		"handler": "accountStatuses",
```suggestion
		"handler": "AccountStatuses",
```

2022-11-09 05:12 UTC, namnhce requested changes

2022-11-09 05:12 UTC, namnhce commented on migrations/test_seed/seed.sql
> +    ('01fb6322-d727-47e3-a242-5039ea4732fc', null, '2022-11-07 09:50:25.714604', '2022-11-07 09:50:25.714604', 'On Leave', 'on leave');
```suggestion
    ('01fb6322-d727-47e3-a242-5039ea4732fc', null, '2022-11-07 09:50:25.714604', '2022-11-07 09:50:25.714604', 'On Leave', 'on-leave');
```

2022-11-09 05:20 UTC, namnhce commented
LGTM 👍

2022-11-09 05:20 UTC, namnhce approved these changes

2022-11-09 05:21 UTC, merged