feat: get feedbacks for user
dwarvesf/fortress-api pull request #115
Opened 2022-12-06 07:15 UTC by nguyennh4522

#### What's this PR do?

- [x] feat: get feedbacks for user

#### What are the relevant Git tickets?

https://www.notion.so/dwarves/4d756d46e90240918cd2505f962cacd1?v=d65335d1772f4532ab1bc274a1ae8c76&p=6f44614d87fc44a489eb4ec0f8c93af8&pm=s

#### Request

```
curl --location --request GET 'http://127.0.0.1:8080/api/v1/feedbacks?status=draft' \
--header 'Authorization: ApiKey PYXXWP25YXJNFGQ6FTRD747FLXK5XIBO4ZC2FMLDWGSMZSEZXFA337RFHSE3PULYPEIDLYJ7MZ4MC43YOA2VCI32TXUVTEZXSQOUJ2Q=' \
--header 'Content-Type: application/json' \
```

#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/104887632/205854115-a47a02a7-69b3-4ddf-b3d5-a1ba6bbb5339.png)

2022-12-06 09:18 UTC, datphamcode295 commented on pkg/handler/feedback/feedback.go
> +		"handler": "Feedback",
```suggestion
		"handler": "feedback",
```

2022-12-07 03:13 UTC, nnhuyhoang requested changes

2022-12-07 03:13 UTC, nnhuyhoang commented on pkg/handler/feedback/feedback.go
> +	rs, total, err := h.store.EmployeeEventTopic.GetByEmployeeID(h.repo.DB(),
should be `GetByEmployeeIDWithPagination`

2022-12-07 04:06 UTC, nnhuyhoang reviewed
LGTM, need @namnhce review for logic

2022-12-07 07:23 UTC, nnhuyhoang approved these changes

2022-12-07 09:52 UTC, merged