feat/api-get-all-position
dwarvesf/fortress-api pull request #12
Opened 2022-11-07 06:19 UTC by datphamcode295

####What's this PR do?
create api to get list values for positions
####Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/55711201/200239103-abc3c497-5bbe-43a7-bc27-0672f02a08ba.png)

// curl
curl 'http://localhost:8200/api/v1/metadata/positions'
-H 'accept: /'
-H 'accept-language: vi,en-US;q=0.9,en;q=0.8'
-H 'content-type: application/json'
-H 'origin: http://localhost:3000/'
-H 'referer: http://localhost:3000/'
-H 'sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"'
-H 'sec-ch-ua-mobile: ?0'
-H 'sec-ch-ua-platform: "macOS"'
-H 'sec-fetch-dest: empty'
-H 'sec-fetch-mode: cors'
-H 'sec-fetch-site: cross-site'
-H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
--compressed

//response:
{"data":[{"id":"frontend","name":"Frontend"},{"id":"backend","name":"Backend"},{"id":"devOps","name":"DevOps"},{"id":"blockchain","name":"Blockchain"},{"id":"project-management","name":"Project-management"}]}

2022-11-07 09:08 UTC, huynguyenh commented
we need to store position in db, please create a db migration and update codebase

2022-11-07 10:37 UTC, huynguyenh commented on pkg/handler/metadata/metadata_test.go
> +	_ "github.com/lib/pq"
sort import

2022-11-07 11:08 UTC, huynguyenh commented on pkg/handler/metadata/metadata.go
> +		"handler": "employee",
update handler name

2022-11-07 11:09 UTC, huynguyenh approved these changes

2022-11-07 11:11 UTC, datphamcode295 commented on pkg/handler/metadata/metadata_test.go
> +	_ "github.com/lib/pq"
thanks you, it's done

2022-11-08 05:33 UTC, namnhce requested changes

2022-11-08 05:33 UTC, namnhce commented on migrations/seed/seed.sql
> +    ('39735742-829b-47f3-8f9d-daf0983914e5', null, '2022-11-07 09:50:25.714604', '2022-11-07 09:50:25.714604', 'project-management', '5');
xuống hàng em ơi

2022-11-08 05:33 UTC, namnhce commented on migrations/test_seed/seed.sql
> +    ('39735742-829b-47f3-8f9d-daf0983914e5', null, '2022-11-07 09:50:25.714604', '2022-11-07 09:50:25.714604', 'project-management', '5');
xuống hàng

2022-11-08 05:33 UTC, namnhce commented on pkg/handler/metadata/testdata/get_positions/200.json
> +      "Name": "frontend",
```suggestion
      "name": "frontend",
```

2022-11-08 05:33 UTC, namnhce commented on pkg/handler/metadata/testdata/get_positions/200.json
> +      "Code": "1"
```suggestion
      "code": "1"
```

2022-11-08 05:33 UTC, namnhce commented on pkg/handler/metadata/testdata/get_positions/200.json
> +      "Code": "1"
applied hết xuống dưới nhé

2022-11-08 07:11 UTC, datphamcode295 commented on pkg/handler/metadata/testdata/get_positions/200.json
> +      "Code": "1"
em chỉnh bên này xong hết r anh @namnhce check lại giúp em xem ok chưa ạ

2022-11-08 08:43 UTC, namnhce requested changes

2022-11-08 08:43 UTC, namnhce commented on migrations/test_seed/seed.sql
> +    ('11ccffea-2cc9-4e98-9bef-3464dfe4dec8', null, '2022-11-07 09:50:25.714604', '2022-11-07 09:50:25.714604', 'frontend', '1'),
a nghĩ là cái này name nên là `Frontend` code là `frontend`
tương tự với ở dưới

2022-11-08 08:44 UTC, namnhce commented on migrations/test_seed/seed.sql
> +    ('11ccffea-2cc9-4e98-9bef-3464dfe4dec8', null, '2022-11-07 09:50:25.714604', '2022-11-07 09:50:25.714604', 'frontend', '1'),
code để đem đi execute query, còn name để display

2022-11-08 08:57 UTC, namnhce commented
LGTM 👍

2022-11-08 08:58 UTC, merged