feat: get countries and cities
dwarvesf/fortress-api pull request #16
Opened 2022-11-08 01:57 UTC by nguyennh4522

#### What's this PR do?

- [x] feat: get countries
- [x] feat: get countries

#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/104887632/200454951-04ad9d1b-5b99-449a-80d3-95aa4560fef9.png)
![image](https://user-images.githubusercontent.com/104887632/200455008-158cb1a7-038e-4fda-9517-38782387f68c.png)

2022-11-08 02:28 UTC, namnhce requested changes

2022-11-08 02:28 UTC, namnhce commented on docs/docs.go
> +                "description": "Get list cities by coutry",
coutry -> country

2022-11-08 02:28 UTC, namnhce commented on docs/swagger.json
> +                "summary": "Get list cities by coutry",
coutry

2022-11-08 02:28 UTC, namnhce commented on docs/docs.go
> +                "summary": "Get list cities by coutry",
coutry

2022-11-08 02:28 UTC, namnhce commented on pkg/store/country/interface.go
> +	All() ([]*model.Country, error)
```suggestion
	All() (countries []*model.Country, err error)
```

2022-11-08 02:28 UTC, namnhce commented on pkg/store/country/interface.go
> +	One(id string) (*model.Country, error)
```suggestion
	One(id string) (country *model.Country, err error)
```

2022-11-08 10:00 UTC, namnhce commented
@nguyennh4522 LG nha em 👍 rebase đi

2022-11-08 10:52 UTC, namnhce requested changes

2022-11-08 10:52 UTC, namnhce commented on docs/swagger.json
> +        "/auth": {
Cái này hình như không ở PR của em phải không

2022-11-08 10:52 UTC, namnhce commented on docs/docs.go
> +                "created_at": {
change to camelCase `created_at` -> `createdAt`
Apply cho mấy cái ở dưới luôn nhé

2022-11-08 10:52 UTC, namnhce commented on docs/swagger.yaml
> +      code:
sort field lại theo thử tự. id -> name -> code -> create -> update-> delete

2022-11-08 10:52 UTC, namnhce commented on docs/swagger.json
> +                "cities": {
sort field lại theo thử tự. id -> name -> code -> create -> update-> delete

2022-11-08 11:21 UTC, nguyennh4522 commented on docs/swagger.yaml
> +      code:
cái này gen ngẫu nhiên, bên swaggo vẫn chưa handle. Ref `https://github.com/go-swagger/go-swagger/issues/2202`

2022-11-08 11:21 UTC, nguyennh4522 commented on docs/swagger.json
> +                "cities": {
như trên

2022-11-08 11:57 UTC, namnhce commented on docs/swagger.json
> +                "cities": {
oke em 🗡️

2022-11-09 01:13 UTC, datphamcode295 approved these changes

2022-11-09 01:43 UTC, namnhce approved these changes

2022-11-09 01:45 UTC, merged