feat: add upload content gcs endpoint
dwarvesf/fortress-api pull request #45
Opened 2022-11-15 08:59 UTC by nnhuyhoang

#### What's this PR do?

- [x] Add new route for uploading content : POST /api/v1/employee/:id/upload-content
- [x] Add new table content for storing media content

#### ERD
<img width="162" alt="Screen Shot 2022-11-22 at 02 44 00" src="https://user-images.githubusercontent.com/71623092/203145471-543d84d8-41cd-43c3-b646-cf7b1bbddb96.png">

#### flow upload content
 validate input (ID, file) -> check file existed -> check employee existed -> create content record -> upload to GCS
 #### curl 
 ```
curl --location --request POST 'http://localhost:8200/api/v1/employees/2655832e-f009-4b73-a535-64c3a22e558f/upload-content' \
--form 'file=@"/Users/hoangnguyen/Desktop/OCPI-2.2-d2.pdf"'
 ```

2022-11-15 08:59 UTC, namnhce commented
Rebase first em.

2022-11-15 09:01 UTC, datphamcode295 commented on .env.sample
> +GCS_PROJECT_ID=projectID
add new line

2022-11-15 18:42 UTC, namnhce requested changes

2022-11-15 18:42 UTC, namnhce commented on pkg/config/config.go
> +	GCSBucketName string
How do we classify which image in the bucket used for avatar image or document files?

2022-11-16 02:14 UTC, namnhce commented
rebase please

2022-11-22 09:56 UTC, nguyennh4522 commented
@nnhuyhoang a rebase + thêm env ở `service/vault/vault.go` luôn nha

2022-11-24 17:22 UTC, datphamcode295 approved these changes

2022-11-24 17:25 UTC, datphamcode295 approved these changes

2022-11-24 17:25 UTC, datphamcode295 approved these changes

2022-11-24 17:30 UTC, datphamcode295 approved these changes

2022-11-24 17:31 UTC, merged