feat: assign member
dwarvesf/fortress-api pull request #58
Opened 2022-11-17 17:31 UTC by nguyennh4522

#### What's this PR do?

- [x] feat: assign member

#### What are the relevant Git tickets?

https://www.notion.so/dwarves/4d756d46e90240918cd2505f962cacd1?v=d65335d1772f4532ab1bc274a1ae8c76&p=cdbb1336773048718aa51932aed6ddfe&pm=s

#### Pseudo code

```
--- ASSIGN
    validate data

    check project, seniority, position existence

    create project slot 
    create project slot positions

    if employee_id != null {
        check employee existence

        create project member
        create project member positions

        if is_lead {
            create project head with technical-lead
        }
    }
--

```

#### CURL

```
curl --location --request POST 'localhost:8080/api/v1/projects/8dc3be2e-19a4-4942-8a79-56db391a0b15/members' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTkzMjExNDIsImlkIjoiMjY1NTgzMmUtZjAwOS00YjczLWE1MzUtNjRjM2EyMmU1NThmIiwiYXZhdGFyIjoiaHR0cHM6Ly9zMy1hcC1zb3V0aGVhc3QtMS5hbWF6b25hd3MuY29tL2ZvcnRyZXNzLWltYWdlcy81MTUzNTc0Njk1NjYzOTU1OTQ0LnBuZyIsImVtYWlsIjoidGhhbmhAZC5mb3VuZGF0aW9uIiwicGVybWlzc2lvbnMiOlsiZW1wbG95ZWVzLnJlYWQiXSwidXNlcl9pbmZvIjpudWxsfQ.GENGPEucSUrILN6tHDKxLMtj0M0REVMUPC7-XhDMpGM' \
--header 'Content-Type: application/json' \
--data-raw '{
    "employeeID": "2655832e-f009-4b73-a535-64c3a22e558f",
    "seniorityID": "01fb6322-d727-47e3-a242-5039ea4732fd",
    "positions": [
        "11ccffea-2cc9-4e98-9bef-3464dfe4dec8"
    ],
    "deploymentType": "official",
    "status": "pending",
    "joinedDate": "2022-11-15",
    "leftDate": "2023-11-15",
    "rate": 10,
    "discount": 1,
    "isLead": true
}'
```

#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/104887632/202515460-fb0c24ce-9b1d-41fb-be85-f9e5a1b459a3.png)

2022-11-17 18:25 UTC, namnhce requested changes

2022-11-17 18:25 UTC, namnhce commented on pkg/handler/project/project.go
> +	}
This part should be in a transaction

2022-11-17 18:25 UTC, namnhce commented on pkg/handler/project/project.go
> +			c.JSON(http.StatusInternalServerError, view.CreateResponse[any](nil, nil, err, body))
Have to roll back the transaction here.

2022-11-17 18:25 UTC, namnhce commented on pkg/handler/project/project.go
> +			c.JSON(http.StatusNotFound, view.CreateResponse[any](nil, nil, ErrEmployeeNotFound, body))
Have to roll back the transaction here.

2022-11-17 18:25 UTC, namnhce commented on pkg/handler/project/project.go
> +			c.JSON(http.StatusInternalServerError, view.CreateResponse[any](nil, nil, done(err), body))
Have to roll back the transaction here.

2022-11-17 18:25 UTC, namnhce commented on pkg/handler/project/project.go
> +				c.JSON(http.StatusInternalServerError, view.CreateResponse[any](nil, nil, done(err), body))
Have to roll back the transaction here.

2022-11-17 18:25 UTC, namnhce commented on pkg/handler/project/project.go
> +				c.JSON(http.StatusInternalServerError, view.CreateResponse[any](nil, nil, done(err), body))
Have to roll back the transaction here.

2022-11-17 18:41 UTC, nguyennh4522 commented on pkg/handler/project/project.go
> +	}
updated

2022-11-17 18:43 UTC, nguyennh4522 commented on pkg/handler/project/project.go
> +			c.JSON(http.StatusInternalServerError, view.CreateResponse[any](nil, nil, done(err), body))
it's already rollback

2022-11-17 18:43 UTC, nguyennh4522 commented on pkg/handler/project/project.go
> +				c.JSON(http.StatusInternalServerError, view.CreateResponse[any](nil, nil, done(err), body))
it's already rollback

2022-11-17 18:43 UTC, nguyennh4522 commented on pkg/handler/project/project.go
> +				c.JSON(http.StatusInternalServerError, view.CreateResponse[any](nil, nil, done(err), body))
it's already rollback

2022-11-18 02:10 UTC, namnhce approved these changes

2022-11-18 02:26 UTC, merged