feat: get employee for selection box
dwarvesf/fortress-api pull request #60
Opened 2022-11-18 04:05 UTC by datphamcode295

#### What's this PR do?

- [x] get list employees for selection box

#### What are the relevant Git tickets?
https://www.notion.so/dwarves/API-to-GET-employee-list-For-selection-box-f13e313855784c78b8357891a093e033

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/55711201/202614202-4f659aff-7d51-44e2-bd9c-2b80fd9b5413.png)

#### Request
```
curl --location --request GET 'http://localhost:8200/api/v1/employees/basic' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTkzMjExNDIsImlkIjoiMjY1NTgzMmUtZjAwOS00YjczLWE1MzUtNjRjM2EyMmU1NThmIiwiYXZhdGFyIjoiaHR0cHM6Ly9zMy1hcC1zb3V0aGVhc3QtMS5hbWF6b25hd3MuY29tL2ZvcnRyZXNzLWltYWdlcy81MTUzNTc0Njk1NjYzOTU1OTQ0LnBuZyIsImVtYWlsIjoidGhhbmhAZC5mb3VuZGF0aW9uIiwicGVybWlzc2lvbnMiOlsiZW1wbG95ZWVzLnJlYWQiXSwidXNlcl9pbmZvIjpudWxsfQ.GENGPEucSUrILN6tHDKxLMtj0M0REVMUPC7-XhDMpGM' \
--data-raw ''
```

#### Response
```
{
    "data": [
        {
            "id": "ecea9d15-05ba-4a4e-9787-54210e3b98ce",
            "fullName": "Nguyễn Hoàng Huy",
            "avatar": "https://s3-ap-southeast-1.amazonaws.com/fortress-images/2830497479497502617.png"
        },
        {
            "id": "2655832e-f009-4b73-a535-64c3a22e558f",
            "fullName": "Phạm Đức Thành",
            "avatar": "https://s3-ap-southeast-1.amazonaws.com/fortress-images/5153574695663955944.png"
        }
    ]
}
```

2022-11-18 04:51 UTC, nguyennh4522 commented on pkg/routes/v1.go
> +	v1.GET("/employees/basic", mw.WithAuth, h.Employee.ListForSelectionBox)
conflict with `/employees/:id`

2022-11-21 02:19 UTC, namnhce requested changes

2022-11-21 02:19 UTC, namnhce commented on pkg/routes/v1_test.go
> +		},
Delete this one

2022-11-21 02:19 UTC, namnhce commented on pkg/store/employee/interface.go
> +	All(db *gorm.DB) (employee []*model.Employee, err error)
Delete this one

2022-11-21 02:19 UTC, namnhce commented on pkg/view/employee.go
> +
Delete this one

2022-11-21 02:29 UTC, datphamcode295 commented on pkg/routes/v1.go
> +	v1.GET("/employees/basic", mw.WithAuth, h.Employee.ListForSelectionBox)
updated

2022-11-21 02:29 UTC, datphamcode295 commented on pkg/routes/v1_test.go
> +		},
updated

2022-11-21 02:29 UTC, datphamcode295 commented on pkg/store/employee/interface.go
> +	All(db *gorm.DB) (employee []*model.Employee, err error)
updated

2022-11-21 02:29 UTC, datphamcode295 commented on pkg/view/employee.go
> +
updated

2022-11-21 04:21 UTC, namnhce approved these changes

2022-11-21 04:22 UTC, merged