chore: update dashboard swagger document
dwarvesf/fortress-api pull request #653
Opened 2023-10-11 02:07 UTC by datphamcode295

#### What's this PR do?

- [x] update dashboard swagger document

2023-10-11 02:57 UTC, hieuphq requested changes

2023-10-11 02:57 UTC, hieuphq commented on pkg/handler/dashboard/dashboard.go
> +// @id getSummary
```suggestion
// @id getProjectSummary
```

2023-10-11 02:57 UTC, hieuphq commented on pkg/view/dashboard.go
> +	rs := make([]ResourceUtilization, 0)
```suggestion
	rs := make([]ResourceUtilization, 0)
```
must modify following golang practice

2023-10-11 04:06 UTC, hieuphq requested changes

2023-10-11 04:06 UTC, hieuphq commented on pkg/view/dashboard.go
> +	rs := make([]ResourceUtilization, len(data))
sai rồi

2023-10-11 04:28 UTC, hieuphq requested changes

2023-10-11 04:28 UTC, hieuphq commented on pkg/handler/dashboard/dashboard.go
> +// @id getWorkUnitDistribution
```suggestion
// @id getWorkUnitDistributionList
```

2023-10-11 04:28 UTC, hieuphq commented on pkg/handler/dashboard/dashboard.go
> +// @id getEngagementInfoDetail
```suggestion
// @id getEngagementInfoDetailList
```

2023-10-11 04:34 UTC, datphamcode295 commented on pkg/handler/dashboard/dashboard.go
> +// @id getEngagementInfoDetail
updated

2023-10-12 10:07 UTC, hieuphq approved these changes

2023-10-13 04:31 UTC, hieuphq approved these changes

2023-10-13 04:31 UTC, merged