chore: update employee swagger document
dwarvesf/fortress-api pull request #654
Opened 2023-10-11 06:04 UTC by datphamcode295

#### What's this PR do?

- [x] update employee swagger

2023-10-11 10:01 UTC, hieuphq requested changes

2023-10-11 10:01 UTC, hieuphq commented on pkg/handler/employee/employee.go
> +// @Param Body body CreateEmployeeRequest true "Body"
```suggestion
// @Param Body body CreateEmployeeQuery true "Body"
```

2023-10-11 10:01 UTC, hieuphq commented on pkg/handler/employee/employee.go
> +// @Param Body body UpdateSkillsRequest true "Body"
```suggestion
// @Param Body body UpdateSkillsQuery true "Body"
```

2023-10-11 10:01 UTC, hieuphq commented on pkg/handler/employee/employee.go
> +// @Param Body body UpdatePersonalInfoRequest true "Body"
```suggestion
// @Param Body body UpdatePersonalInfoQuery true "Body"
```

2023-10-11 17:52 UTC, datphamcode295 commented on pkg/handler/employee/employee.go
> +	}
I already added view.UUID to replace model.UUID to solve this

2023-10-12 03:12 UTC, hieuphq requested changes

2023-10-12 03:12 UTC, hieuphq commented on pkg/view/pagination.go
> +	Standardized bool   `json:"-" form:"-" swaggerignore:"true"`
??

2023-10-12 03:12 UTC, hieuphq commented on pkg/view/pagination.go
> +}
??

2023-10-12 03:39 UTC, datphamcode295 commented on pkg/view/pagination.go
> +}
này bên handler có dùng á anh

2023-10-12 08:59 UTC, hieuphq requested changes

2023-10-12 08:59 UTC, hieuphq commented on pkg/controller/employee/list.go
> +
??

2023-10-12 08:59 UTC, hieuphq commented on pkg/controller/employee/list.go
>  	errors "errors"
??

2023-10-12 08:59 UTC, hieuphq commented on pkg/handler/employee/employee.go
> +// @Param Body body GetListEmployeeInput true "Body"
```suggestion
// @Param Body body GetListEmployeeQuery true "Body"
```

2023-10-12 08:59 UTC, hieuphq commented on pkg/handler/employee/employee.go
> +// @Param roleID body string true "Account role ID"
```suggestion
// @Param roleID body UpdateRoleRequest true "Account role ID"
```

2023-10-12 10:39 UTC, hieuphq approved these changes

2023-10-13 04:24 UTC, merged