feat: api get list senitorities
dwarvesf/fortress-api pull request #9
Opened 2022-11-07 05:48 UTC by datphamcode295

What's this PR do?
create api to get list values for senitorities
Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/55711201/200235167-c27694a1-ccd3-4f65-b9b0-ee8f56f405be.png)

// curl
curl 'http://localhost:8200/api/v1/metadata/senitorities'
-H 'accept: /'
-H 'accept-language: vi,en-US;q=0.9,en;q=0.8'
-H 'content-type: application/json'
-H 'origin: http://localhost:3000/'
-H 'referer: http://localhost:3000/'
-H 'sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"'
-H 'sec-ch-ua-mobile: ?0'
-H 'sec-ch-ua-platform: "macOS"'
-H 'sec-fetch-dest: empty'
-H 'sec-fetch-mode: cors'
-H 'sec-fetch-site: cross-site'
-H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
--compressed

//response:
{"data":[{"id":"left","name":"Left"},{"id":"probation","name":"Probation"},{"id":"full-time","name":"Full-time"},{"id":"contractor","name":"Contractor"}]}

2022-11-07 09:10 UTC, huynguyenh commented
same, this one please create db table for it

2022-11-07 13:24 UTC, namnhce requested changes

2022-11-09 09:44 UTC, namnhce commented
Format lại description PR description nha em

2022-11-10 02:09 UTC, namnhce approved these changes

2022-11-10 02:11 UTC, merged